version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: fcx-mysql-demo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: fcx
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - './docker/.docker/data/db:/var/lib/mysql'
      - './docker/.docker/mnt:/mnt'
    ports:
      - 3307:3306

  redis:
    image: 'redis:6-alpine'
    container_name: fcx-redis-cache
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: fcx-backend
  #   user: node
  #   ports:
  #     - 5000:5000
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - redis
  #     - mysql
  #   links:
  #     - redis

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.6.2'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.6.0'
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
