app:
  name: fcxv2-backend
  port: 3000
  env: development
  url: 127.0.0.1
  prefix: api/v1
  password_secret: 0470a528a1d1687c9ab7b2857ac3d3394a5fc37e1eec91652ca934722ac2bbfe
  salt_round: 10
  token_expire: 60000s
  jwt_access_token_secret: 0470a528a1d1687c9ab7b2857ac3d3394a5fc37e1eec91652ca934722ac2bbfe
  jwt_access_token_expiration_time: 86400s
  jwt_refresh_token_secret: 0470a528a1d1687c9ab7b2857ac3d3394a5fc37e1eec91652ca934722ac2bbfe
  jwt_refresh_token_expiration_time: 604800s
  jwt_verify_email_token_secret: 0470a528a1d1687c9ab7b2857ac3d3394a5fc37e1eec91652ca934722ac2bbfe
  jwt_verify_email_token_expiration_time: 86400s

master:
  type: mysql
  host: 'http://127.0.0.1'
  port: 3307
  username: admin
  password: 1
  database: test
  logging: true
  entities:
    - 'dist/**/*.entity{.ts,.js}'

report:
  type: mysql
  host: 'http://127.0.0.1'
  port: 3307
  username: admin
  password: 1
  database: test
  logging: true
  entities:
    - 'dist/**/*.entity{.ts,.js}'

redis:
  host: 'http://127.0.0.1'
  port: 3308

mnemonic: 'december carpet ranch page like milk monster correct source ten human indicate'
base_derivation_path: "44'/60'/0'/0"
network_id: 15
chain_id: 15
address_exchange: '0xF54b3294616d39749732Ac74F234F46C9ABf29C4'

sentry_dns: 'https://db92c0c8674b4f3480908dfef1fde708@o736520.ingest.sentry.io/5785081'

cron:
  enable: false

mail:
  host: 'smtp.mailtrap.io'
  port: 2525
  account: 'c2a066cdf3d560'
  password: '399dc51ba1eb5e'

coinmarketcap:
  base_url: 'https://pro-api.coinmarketcap.com'
  prefix_get_price: '/v1/cryptocurrency/quotes/latest'
  api_key: '1111'

xe_currencies:
  fixer_access_key: '1c848d80890798cfdb8bc90b1a723ce4'
  fixer_api_currencies: 'http://data.fixer.io/api/latest'
  fixer_base_currency: 'USD'

base_pnl: 'USD'

ticker:
  interval: 3000
fcx:
  page: https://fcx3.sotatek.works
  admin: https://fcx3-admin.sotatek.works
